lib/slackish_phoenix_web/router.ex
defmodule SlackishPhoenixWeb.Router do
  use SlackishPhoenixWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :detect_user_in_session
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SlackishPhoenixWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/home/:company", HomeController, :index
    resources "/companies", CompanyController, only: [:new, :create]
  end

  scope "/auth", SlackishPhoenixWeb do
    pipe_through :browser

    get "/logout", AuthController, :logout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", SlackishPhoenixWeb do
  #   pipe_through :api
  # end

  defp detect_user_in_session(conn, _params) do
    user =
      conn
      |> get_session(:current_user)
      |> SlackishPhoenix.Auth.get_user()

    case user do
      nil -> conn
      user -> conn |> assign(:user, user)
    end
  end
end

lib/slackish_phoenix/companies/companies.ex
defmodule SlackishPhoenix.Companies do
  @moduledoc """
  The Companies context.
  """

  import Ecto.Query, warn: false
  alias SlackishPhoenix.Repo

  alias SlackishPhoenix.Auth.User
  alias SlackishPhoenix.Companies.Company

  @doc """
  Returns the list of companies.

  ## Examples

      iex> list_companies()
      [%Company{}, ...]

  """
  def list_companies do
    Repo.all(Company)
  end

  @doc """
  Gets a single company.

  Raises `Ecto.NoResultsError` if the Company does not exist.

  ## Examples

      iex> get_company!(123)
      %Company{}

      iex> get_company!(456)
      ** (Ecto.NoResultsError)

  """
  def get_company!(id), do: Repo.get!(Company, id)

  @doc """
  Creates a company.

  ## Examples

      iex> create_company(%{field: value})
      {:ok, %Company{}}

      iex> create_company(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_company(attrs \\ %{}) do
    %Company{}
    |> Company.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a company.

  ## Examples

      iex> update_company(company, %{field: new_value})
      {:ok, %Company{}}

      iex> update_company(company, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_company(%Company{} = company, attrs) do
    company
    |> Company.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Company.

  ## Examples

      iex> delete_company(company)
      {:ok, %Company{}}

      iex> delete_company(company)
      {:error, %Ecto.Changeset{}}

  """
  def delete_company(%Company{} = company) do
    Repo.delete(company)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking company changes.

  ## Examples

      iex> change_company(company)
      %Ecto.Changeset{source: %Company{}}

  """
  def change_company(%Company{} = company) do
    Company.changeset(company, %{})
  end

  @doc """
  Associates an `%SlackishPhoenix.Auth.User` with a `%SlackishPhoenix.Companies.Company`.
  """
  def add_user_to_company(
        %SlackishPhoenix.Auth.User{} = user,
        %SlackishPhoenix.Companies.Company{} = company
      ) do
    user = user |> Repo.preload(:companies)
    companies = (user.companies ++ [company]) |> Enum.map(&Ecto.Changeset.change/1)

    user
    |> Ecto.Changeset.change()
    |> Ecto.Changeset.put_assoc(:companies, companies)
    |> Repo.update!()

    {:ok}
  end

  @doc false
  def list_all_companies_of_user(%User{} = user) do
    user = user |> Repo.preload(:companies)

    user.companies
  end

  @doc false
  def list_all_users_of_company(%Company{} = company) do
    company = company |> Repo.preload(:users)

    company.users
  end

  @doc false
  def get_company_for_user!(%User{} = user, company_id) do
    build_company_for_user_query(user, company_id)
    |> Repo.one!()
  end

  @doc false
  def get_company_for_user(%User{} = user, company_id) do
    build_company_for_user_query(user, company_id)
    |> Repo.one()
  end

  defp build_company_for_user_query(%User{} = user, company_id) do
    query =
      from c in Company,
        join: u in "company_user",
        on: u.company_id == c.id,
        where: u.user_id == ^user.id,
        where: c.id == ^company_id,
        select: c

    query |> first
  end
end

lib/slackish_phoenix/companies/company.ex
defmodule SlackishPhoenix.Companies.Company do
  use Ecto.Schema
  import Ecto.Changeset

  @derive {Jason.Encoder, only: [:name, :id]}

  schema "companies" do
    field :name, :string

    belongs_to :owner, SlackishPhoenix.Auth.User
    many_to_many :users, SlackishPhoenix.Auth.User, join_through: "company_user"

    timestamps()
  end

  @doc false
  def changeset(company, attrs) do
    company
    |> cast(attrs, [:name, :owner_id])
    |> validate_required([:name, :owner_id])
  end
end

lib/slackish_phoenix_web/controllers/company_controller.ex
defmodule SlackishPhoenixWeb.CompanyController do
  use SlackishPhoenixWeb, :controller

  plug SlackishPhoenixWeb.Plugs.RequireAuth

  alias SlackishPhoenix.Companies
  alias SlackishPhoenix.Auth
  alias SlackishPhoenix.Companies.Company

  def new(conn, _params) do
    companies = Companies.list_all_companies_of_user(conn.assigns[:user])
    changeset = Company.changeset(%Company{}, %{})

    render(conn, "new.html", changeset: changeset, companies: companies)
  end

  def create(conn, %{"company" => params}) do
    user = conn.assigns[:user]

    case Companies.create_company(params |> Map.put("owner_id", user.id)) do
      {:ok, company} ->
        Auth.assign_current_company(user, company.id)
        Companies.add_user_to_company(user, company)
        conn |> redirect(to: "/home/#{company.id}")

      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

lib/slackish_phoenix_web/views/company_view.ex
defmodule SlackishPhoenixWeb.CompanyView do
  use SlackishPhoenixWeb, :view
end

lib/slackish_phoenix_web/templates/company/new.html.eex
<div class="bg-grey-lightest h-screen">
    <%= if length(@companies) > 0 do %>
    <div class="container mx-auto flex justify-content mb-4">
        <div class="w-2/3 mx-auto my-4">
            <div class="bg-blue-lightest border-l-4 border-blue text-blue-dark p-4" role="alert">
                <p class="font-bold">Almost there!</p>
                <p>In order to proceed, you need to select a company.</p>
            </div>
            <p class="block tracking-wide text-grey-darker text-md font-bold mb-2 mt-4">
              Pick one of your companies
            </p>

            <ul class="list-reset flex flex-col">
              <%= for {company,index} <- Enum.with_index(@companies) do %>
                <li class="<%= index == 0 && "rounded-t" %> <%= index == length(@companies) - 1 && "rounded-b" %> relative -mb-px block border p-4 border-grey">
                  <a href="<%= "/home/#{company.id}" %>" class="flex justify-between text-blue-dark no-underline hover:text-blue-light">
                    <span><%= company.name %></span>
                    <svg height="15" width="15" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M20 10a10 10 0 1 1-20 0 10 10 0 0 1 20 0zm-2 0a8 8 0 1 0-16 0 8 8 0 0 0 16 0zm-8 2H5V8h5V5l5 5-5 5v-3z"/></svg>
                  </a>
                </li>
              <% end %>
            </ul>
        </div>
    </div>
    <% end %>
    <div class="container mx-auto flex justify-content">
        <div class="w-2/3 mx-auto my-4">
            <%= if length(@companies) == 0 do %>
              <div class="bg-blue-lightest border-l-4 border-blue text-blue-dark p-4" role="alert">
                  <p class="font-bold">Almost there!</p>
                  <p>In order to proceed, you need to create a company.</p>
              </div>
            <% else %>
              <div class="bg-blue-lightest border-l-4 border-blue text-blue-dark p-4" role="alert">
                  <p>Alternatively, you can create a new one.</p>
              </div>
            <% end %>

            <%= form_for @changeset, Routes.company_path(@conn, :create), fn f -> %>
                <div class="flex flex-wrap -mx-3 mb-6 mt-6">
                    <div class="w-full px-3">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="company-name">
                            Company Name
                        </label>
                        <%= text_input f, :name, placeholder: "Name", class: "appearance-none block w-full bg-white text-grey-darker border border-grey-light rounded py-4 px-4 mb-3" %>
                        <%= error_tag f, :name %>
                    </div>
                </div>

                <div class="w-full">
                    <%= submit "Create Company", class: "py-4 px-6 border border-purple-lightest bg-white rounded text-purple-light" %>
                </div>
            <% end %>
        </div>
    </div>
</div>